"""Initial migration

Revision ID: 5a35887143bc
Revises: 
Create Date: 2023-12-28 21:51:40.185421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5a35887143bc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scheduled_tasks')
    op.drop_table('user_specific_data')
    op.drop_table('conversations')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.INTEGER(), server_default=sa.text("nextval('users_user_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name_first', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('name_last', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('location', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('username', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('salt', sa.VARCHAR(length=29), autoincrement=False, nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(length=60), autoincrement=False, nullable=False),
    sa.Column('birth_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('conversation_index', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('bing_searches', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('lexi_learns', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('encrypted_google_details', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.Column('google_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('gmail_access', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('google_calendar_access', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('theme_selection', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('text_color', sa.VARCHAR(length=7), autoincrement=False, nullable=True),
    sa.Column('background_color', sa.VARCHAR(length=7), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('user_id', name='users_pkey'),
    sa.UniqueConstraint('username', name='users_username_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('conversations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_on', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('conversation_id', sa.VARCHAR(length=6), autoincrement=False, nullable=True),
    sa.Column('last_updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('app_messages_content', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.Column('model_assistant_id', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('model_thread_id', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('model_messages', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.Column('metrics', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name='conversations_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='conversations_pkey'),
    sa.UniqueConstraint('conversation_id', name='conversations_conversation_id_key')
    )
    op.create_table('user_specific_data',
    sa.Column('data_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('data_category', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('data_content', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name='user_specific_data_user_id_fkey'),
    sa.PrimaryKeyConstraint('data_id', name='user_specific_data_pkey')
    )
    op.create_table('scheduled_tasks',
    sa.Column('task_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('data_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('conversation_id', sa.VARCHAR(length=4), autoincrement=False, nullable=True),
    sa.Column('function_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('arguments', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('annotations', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('repeat_each', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('notify_to', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('start_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('end_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name='scheduled_tasks_user_id_fkey'),
    sa.PrimaryKeyConstraint('task_id', name='scheduled_tasks_pkey')
    )
    # ### end Alembic commands ###
